# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  kb_layout = us,fi
  kb_options = caps:super,grp:alt_shift_toggle

  # Change speed of keyboard repeat
  repeat_rate = 60
  repeat_delay = 220

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  sensitivity = -0.05
  accel_profile = flat
  scroll_factor = 0.8

 }

# Scroll faster in the terminal
# windowrule = scrolltouchpad 1.5, tag:terminal

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace

cursor {
  inactive_timeout = 2 # Number of seconds before disappearing
  hide_on_key_press = true # Cursor hide when key press
}

misc {
  mouse_move_enables_dpms=true
  key_press_enables_dpms=true
}

